
POST http://127.0.0.1:8000/api/v1/auth/signup/
Content-Type: application/json

{
    "username": "root_new",
    "email": "user@no-admin.ru"
}

###

POST http://127.0.0.1:8000/api/v1/auth/token/
Content-Type: application/json

{
    "username": "admin-user",
    "confirmation_code": 411389
}

###

{
  "refresh": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTcwNDUyODYxMSwiaWF0IjoxNzA0NDQyMjExLCJqdGkiOiIwYjRjYWMzMzc3MTI0ZmQ0YTAwMDc3NGZhODBmZDFiNCIsInVzZXJfaWQiOjV9.zET_tIgOJ-eI-5KyKhBDD5OAr0Pwrq7OGyFcN-xUHw8",
  "access": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzA0NTI4NjExLCJpYXQiOjE3MDQ0NDIyMTEsImp0aSI6ImQ5NzE5NzNiNjk0ZDRjMmNhNTVlODI4ZTAxYmJjY2MzIiwidXNlcl9pZCI6NX0.goaa5fYUJf5L4S7tqpdwatyaJnaBvHelBDaEXsu_0_Q"
}

###

GET http://127.0.0.1:8000/api/v1/users/
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzA0ODgwMDEzLCJpYXQiOjE3MDQ3OTM2MTMsImp0aSI6IjYxOTg2OGYyNmIwYTQ4MTdiNmYyZWEyNzJmYzI0ZWVkIiwidXNlcl9pZCI6MX0.W-cIkNGrNIz6AUYBjl0khKVHV4K4jSz3V4fFQ6e8xzE

###
{
    "username": "test_user_new",
    "email": "example@yandex.ru"
}

###

GET http://127.0.0.1:8000/
Content-Type: application/json
Authorization: Token 9e521804f745d52b332ee673924d09c3f437c84e

###

GET http://127.0.0.1:8000/api/v1/users/me/
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzA0ODgwMDEzLCJpYXQiOjE3MDQ3OTM2MTMsImp0aSI6IjYxOTg2OGYyNmIwYTQ4MTdiNmYyZWEyNzJmYzI0ZWVkIiwidXNlcl9pZCI6MX0.W-cIkNGrNIz6AUYBjl0khKVHV4K4jSz3V4fFQ6e8xzE


###
admin-user
###

POST http://127.0.0.1:8000/api/v1/titles/
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzA0OTYyNTQ3LCJpYXQiOjE3MDQ4NzYxNDcsImp0aSI6IjAyMjgwYWEwMzc1OTQ1YjViZDNjNjVkNmViNDY2YjM2IiwidXNlcl9pZCI6Mn0.9lNcsAm5BWADMfxs7Edr_6IojdJrhpRUgP4ibBExcrg

{
    "name": "Admin Title",
    "year": 2020,
    "description": "Test title by admin",
    "genre": [
        "admin-genre-slug",
        "superuser-genre-slug"
    ],
    "category": "admin-slug"
}

###

DELETE http://127.0.0.1:8000/api/v1/users/regular-user/
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzA0ODgwMDEzLCJpYXQiOjE3MDQ3OTM2MTMsImp0aSI6IjYxOTg2OGYyNmIwYTQ4MTdiNmYyZWEyNzJmYzI0ZWVkIiwidXNlcl9pZCI6MX0.W-cIkNGrNIz6AUYBjl0khKVHV4K4jSz3V4fFQ6e8xzE
