
POST http://127.0.0.1:8000/api/v1/auth/signup/
Content-Type: application/json

{
    "username": "regular_user",
    "email": "example@yandex.ru"
}

###

POST http://127.0.0.1:8000/api/v1/auth/token/
Content-Type: application/json

{
    "username": "regular_user",
    "confirmation_code": 678076
}

###

{
  "refresh": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTcwNDM5NTU4MCwiaWF0IjoxNzA0MzA5MTgwLCJqdGkiOiI1ODhjNTg3MmZmNTc0ZGY0ODcxNDAzNWIwM2IwNmQ5YyIsInVzZXJfaWQiOjF9.D_NbElY15eMZMa8uRWWenNV2FhtRbjdZzNPMik0NCtQ",
  "access": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzA0Mzk1NTgwLCJpYXQiOjE3MDQzMDkxODAsImp0aSI6IjQ3YmU2NjQyNDhkMzQ1NjJhMzIwNDQ2OWQ3NWI0ZjUzIiwidXNlcl9pZCI6MX0.dD9Nnfpvi4noI2iBkrJJaRQRQrDB9stXOFirjh9o81Q"
}

###

GET http://127.0.0.1:8000/api/v1/users/
Content-Type: application/json
Authorization: Token 9e521804f745d52b332ee673924d09c3f437c84e

###

GET http://127.0.0.1:8000/
Content-Type: application/json
Authorization: Token 9e521804f745d52b332ee673924d09c3f437c84e

###

PATCH http://127.0.0.1:8000/api/v1/posts/3/comments/5/
Content-Type: application/json
Authorization: Token 9e521804f745d52b332ee673924d09c3f437c84e

{
    "text": "тест 3 new"
}
###

GET http://127.0.0.1:8000/api/v1/posts/3/comments/1/
Content-Type: application/json
Authorization: Token 9e521804f745d52b332ee673924d09c3f437c84e
