# Generated by Django 3.2 on 2024-01-03 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20240103_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='confirmation_code',
            field=models.IntegerField(null=True, verbose_name='Код подтверждения'),
        ),
    ]
