# Generated by Django 3.2 on 2024-01-03 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_role'),
        ('users', '0004_auto_20240103_1748'),
    ]

    operations = [
    ]
