# Generated by Django 3.2 on 2024-01-05 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20240103_2115'),
        ('users', '0008_auto_20240104_0322'),
    ]

    operations = [
    ]
