# Generated by Django 3.2 on 2024-01-09 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'default_related_name': 'author', 'verbose_name': 'Пользователь', 'verbose_name_plural': 'пользователи'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('user', 'Пользователь'), ('moderator', 'Модератор'), ('admin', 'Администратор')], default='user', max_length=32, verbose_name='Пользовательская роль'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.SlugField(max_length=150, unique=True, verbose_name='Логин'),
        ),
    ]
