# Generated by Django 3.2 on 2024-01-10 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20240109_1657'),
        ('users', '0012_auto_20240109_1716'),
    ]

    operations = [
    ]
