# Generated by Django 3.2 on 2024-01-04 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_review_user_following_unique'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='review',
            name='user_following_unique',
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('author', 'title'), name='author_title_unique'),
        ),
    ]
