# Generated by Django 3.2 on 2024-01-04 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_auto_20240104_2301'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='review',
            name='author_title_unique',
        ),
    ]
