# Generated by Django 3.2 on 2024-01-09 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0011_auto_20240109_1657'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='review',
            name='author_title_unique',
        ),
    ]
