# Generated by Django 3.2 on 2024-01-09 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0013_review_author_title_unique'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genretitle',
            options={'default_related_name': 'genretitle', 'verbose_name': 'Жанр', 'verbose_name_plural': 'жанры'},
        ),
        migrations.AlterField(
            model_name='genretitle',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genretitle', to='reviews.genre'),
        ),
        migrations.AlterField(
            model_name='genretitle',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genretitle', to='reviews.title'),
        ),
    ]
