# Generated by Django 3.2 on 2024-01-10 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0011_auto_20240109_1132'),
        ('reviews', '0014_auto_20240109_2223'),
    ]

    operations = [
    ]
